# Generated by Django 5.1.2 on 2024-10-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default=88812514, max_length=20),
            preserve_default=False,
        ),
    ]
