# Generated by Django 5.1.2 on 2024-11-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_atividades_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividades',
            name='status_atividade',
            field=models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('EXECUTANDO', 'EXECUTANDO'), ('FINALIZADO', 'FINALIZADO')], default='PENDENTE', max_length=12),
        ),
    ]
