# Generated by Django 5.1.2 on 2024-11-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_atividades_status_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividades',
            name='Prioridade',
            field=models.CharField(choices=[('BAIXA', 'BAIXA'), ('MEDIA', 'MEDIA'), ('ALTA', 'ALTA')], default='BAIXA', max_length=12),
        ),
        migrations.AddField(
            model_name='projetos',
            name='Prioridade',
            field=models.CharField(choices=[('BAIXA', 'BAIXA'), ('MEDIA', 'MEDIA'), ('ALTA', 'ALTA')], default='BAIXA', max_length=12),
        ),
    ]
