# Generated by Django 5.1.2 on 2024-11-12 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_atividades_prioridade_projetos_prioridade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividades',
            old_name='Prioridade',
            new_name='prioridade',
        ),
        migrations.RenameField(
            model_name='projetos',
            old_name='Prioridade',
            new_name='prioridade',
        ),
    ]
