# Generated by Django 5.1.2 on 2024-11-12 02:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_prioridade_atividades_prioridade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='data_fim',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projetos',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
