# Generated by Django 5.1.2 on 2024-11-17 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_projetos_data_fim_projetos_data_inicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
