# Generated by Django 5.1.2 on 2024-11-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='raisson@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='raisson', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='POSDFS_Python', max_length=50),
        ),
    ]
