# Generated by Django 5.1.2 on 2024-11-17 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_userprofile_email_alter_userprofile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
