# Generated by Django 5.1.2 on 2024-11-17 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_userprofile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='first_name',
        ),
    ]
